# Fix Colors
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"

set -g prefix C-a

# Scrolling
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows
set-option -g renumber-windows on

# Statusline Colors
set -g status-style bg=terminal,fg=terminal

# Statusline location
set -g status-position bottom

# Current window name bold
set -g window-status-current-style fg=terminal,bold

# Increase left length
set -g status-left-length 20

# rose-pine
set -g status-bg "#191724"  # $background
set -g status-fg "#EAD9C9"  # $color7

# Separators in the status bar
set -g status-left-style bg="#191724",fg="#F5E0DC"
set -g status-right-style bg="#282828",fg="#ebdbb2"

# Status left and right sections (optional, customizable)
set -g status-left "#[bg=#191724,fg=#7F9CDA] [ tmux ] #[default]"
# Right status settings
set -g status-right "#[fg=#F5E0DC,bg=#191724] Session: #S "

# Inactive pane border: Match `client.unfocused`
set -g pane-border-style fg=#665c54

# Active pane border: Match `client.focused`
set -g pane-active-border-style fg=#a89984

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'ssh psql mysql wscat'

bind-key x kill-pane

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'L' send -X end-of-line
bind-key -T copy-mode-vi 'H' send -X start-of-line

unbind-key \{
bind-key -T prefix \{ copy-mode

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
